config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :users
  resources :projects do
    resources :tasks, only: %i(create destroy new) do
      resources :cards, only: %i(new create)
    end
    member do
      get "/show_member", to: "projects#show_member"
      post "/add_member", to: "projects#add_member"
      delete "/delete_member", to: "projects#remove_member"
    end
  end
  resources :cards, only: %i(show edit update destroy) do
    resources :events, only: %i(create), shallow: true
    member do
      post "/assign/:user_id", to: "assign#create", :as => "assign"
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :cards, dependent: :destroy
  validates :name, presence: true
  scope :order_by_created_at_asc, -> {order created_at: :asc}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout "user_working"
  before_action :authenticate_user!
  before_action :get_project
  before_action :logged_in?, only: %i(create destroy new)

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build task_params
    if @task.save
      flash[:success] = t "task.created"
      redirect_to project_path(@project)
    else
      flash[:danger] = t "task.uncreated"
      redirect_to new_project_task_path(@project)
    end
  end

  def destroy
    correct_project
    if @task.destroy
      flash[:success] = t "task.deleted"
    else
      flash[:danger] = t "task.delete_error"
    end
    redirect_back fallback_location: project_path(@project)
  end

  private

  def task_params
    params.require(:task).permit :name
  end

  def correct_project
    @project = current_user.projects.find_by id: params[:project_id]
    @task = @project.tasks.find_by id: params[:id]
    return if @task && @project
    flash[:danger] = t "task.not_found"
    redirect_to :root
  end

  def get_project
    @project = Project.find_by id: params[:project_id]
    return unless @project.nil?
    flash[:danger] = t "project.project_not_found"
    redirect_to projects_path
  end
end

app/views/tasks/_card.html.erb
<%= link_to  card_path(card.id), class: "list-card" do %>
  <div class="list-card-cover"></div>
  <span class="icon-sm icon-edit list-card-operation dark-hover"></span>
  <div class="list-card-stickers-area">
    <div class="stickers"></div>
  </div>
  <div class="list-card-details">
    <div class="list-card-labels"></div>
    <span class="list-card-title">
      <%= card.name %>
    </span>
    <div class="list-card-members">
      <%= card.describe %>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="list-wrapper">
  <div class="list">
    <div class="list-header">
      <div class="list-header-target"></div>
      <textarea class="list-header-name mod-list-name list-name"
        aria-label="<%= task.name %>"
        spellcheck="false" dir="auto" maxlength="512">
        <%= task.name %>
      </textarea>
      <div class="list-header-extras">
        <%= link_to project_task_path(@project, task),
          class: "list-header-extras-menu dark-hover icon-lg",
          method: :delete , data: {confirm: t("task.delete_confirm")} do  %>
          <button class="btn btn-danger btn-xs">X</button>
        <% end %>
      </div>
      <p class="list-header-num-cards">
        <%= pluralize task.cards.count, t("card.card") %>
      </p>
    </div>
    <div class="list-cards">
      <% task.cards.each do |card| %>
        <%= render "tasks/card", {card: card} %>
      <% end %>
    </div>
    <%= link_to new_project_task_card_path(@project, task),
      class: "open-card-composer" do %>
      <span class="icon-sm glyphicon glyphicon-plus"></span>
      <span><%= t "card.add_card" %></span>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<% provide :title, t("task.create_task") %>
<div class="row">
  <h1><%= t "task.create_task" %></h1>
  <div class="col-md-6 col-md-offset-3 portfolio-item">
    <%= form_for @task, url: project_tasks_path do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="field">
        <%= f.text_field :name, class: "form-control",
          placeholder: t("task.placeholder")%>
      </div>
      <%= f.submit t("task.create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>