config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :users
  resources :projects do
    resources :tasks, only: %i(create destroy new) do
      resources :cards, only: %i(new create)
    end
    member do
      get "/show_member", to: "projects#show_member"
      post "/add_member", to: "projects#add_member"
      delete "/delete_member", to: "projects#remove_member"
    end
  end
  resources :cards, only: %i(show edit update destroy) do
    resources :events, only: %i(create), shallow: true
    member do
      post "/assign/:user_id", to: "assign#create", :as => "assign"
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_show_flash.html.erb
<% unless flash.empty? %>
  <div class="modal fade" id="myModal" role="dialog" style="display: none;">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button"
            class="btn btn-default" data-dismiss="modal">
            <%= t "side_bar.close" %>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_side_bar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to t("side_bar.dashboard"), projects_path %>
    </li>
    <li>
      <%= link_to t("side_bar.new_project"), new_project_path %>
    </li>
    <li>
      <%= link_to t("static.profile"), current_user %>
    </li>
    <li>
      <%= link_to t("static.settings"), edit_user_path(current_user) %>
    </li>
    <li>
      <%= link_to t("side_bar.sign_out"), logout_path, method: :delete %>
    </li>
  </ul>
</div>

app/views/shared/_side_bar_working.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to t("side_bar.dashboard"), projects_path %>
    </li>
    <li>
      <%= link_to t("side_bar.new_project"), new_project_path %>
    </li>
    <li>
      <%= link_to t("side_bar.project"), @project %>
    </li>
    <li>
      <%= link_to t("side_bar.member"),
        show_member_project_path(:id => @project.id) %>
    </li>
    <li>
      <%= link_to t("task.create_task"),
        new_project_task_path(@project) %>
    </li>
    <li>
      <%= link_to t("side_bar.sign_out"), logout_path, method: :delete %>
    </li>
  </ul>
</div>