config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :users
  resources :projects do
    resources :tasks, only: %i(create destroy new) do
      resources :cards, only: %i(new create)
    end
    member do
      get "/show_member", to: "projects#show_member"
      post "/add_member", to: "projects#add_member"
      delete "/delete_member", to: "projects#remove_member"
    end
  end
  resources :cards, only: %i(show edit update destroy) do
    resources :events, only: %i(create), shallow: true
    member do
      post "/assign/:user_id", to: "assign#create", :as => "assign"
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :relationships
  has_many :users, through: :relationships
  validates :name, presence: true,
    length: {maximum: Settings.constant.name_max_length}
  scope :order_created_at, -> {order created_at: :desc}
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout :resolve_layout
  before_action :authenticate_user!
  before_action :get_project, only: %i(show_member add_member show)
  include ProjectsHelper

  def index
    @project = current_user.projects.order_created_at
      .page(params[:page]).per Settings.constant.project_per_page
  end

  def show
    @tasks = @project.tasks.order_by_created_at_asc
  end

  def new
    @project = Project.new
  end

  def create
    ActiveRecord::Base.transaction do
      @project = Project.new project_create_params
      @project.save!
      relationship = @project.relationships
        .build user: current_user, is_manager: true
      relationship.save!
      create_deault_tasks
      redirect_to project_path @project
    end
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def show_member
    @member = @project.users
  end

  def add_member
    flash.clear
    user = User.find_by email: params[:email].downcase
    if user.nil?
      flash[:danger] = t "member.email_not_found"
    elsif get_relationship(user.id).present?
      flash[:danger] = t "member.user_in_project"
    else
      relationship = Relationship.new project_id: @project.id,
        user_id: user.id
      flash[:danger] = t "member.add_error" unless relationship.save
    end
    @member = @project.users
    render :show_member
  end

  def remove_member
    relationship = get_relationship params[:user_id]
    if relationship.delete
      redirect_to show_member_project_path
    else
      flash[:danger] = t "member.remove_error"
      render :show_member
    end
  end

  private

  def project_create_params
    params.require(:project).permit :name, :describe
  end

  def get_project
    @project = Project.find_by id: params[:id]
    return unless @project.nil?
    flash[:danger] = t "project.project_not_found"
    redirect_to projects_path
  end

  def get_relationship user_id
    Relationship.find_by project_id: params[:id], user_id: user_id
  end

  def resolve_layout
    case action_name
    when "index", "new", "create"
      "user"
    else
      "user_working"
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def manager_hightlight member
    return "btn-primary" if is_manager? member
    "btn-success"
  end

  def is_manager? member
    Relationship.find_by(user_id: member.id, project_id: @project.id)
      .is_manager?
  end

  def is_project_manager?
    @is_manager ||= current_user.is_project_manager? @project
  end

  def create_deault_tasks
    @project.tasks.create! name: t("default_task")
  end
end

app/views/projects/index.html.erb
<% provide :title, t("project.all_project") %>
<h1 class="my-4"><%= t "project.all_project" %></h1>
<div class="row">
  <% @project.each do |project| %>
    <div class="col-lg-3 col-md-4 col-sm-6 portfolio-item">
      <%= link_to project do %>
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">
              <%= project.name %>
            </h4>
            <p class="card-text"><%= project.describe %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-md-2 col-md-offset-5">
    <%= paginate @project %>
  </div>
</div>

app/views/projects/new.html.erb
<% provide :title, t("project.new_project") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= t "project.new_project" %></h1>
    <%= form_for @project do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :describe %>
      <%= f.text_area :describe, class: "form-control" %>
      <%= f.submit t("project.new_project"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<% provide :title, @project.name %>
<div class="row board-main-content">
  <div class="board-canvas">
    <div id="board">
      <% @tasks.each do |task| %>
        <%= render task %>
      <% end %>
      <div class="list-wrapper">
        <div class="list">
          <%= link_to new_project_task_path(:project_id => @project.id),
            class: "open-card-composer" do %>
            <span class="icon-sm glyphicon glyphicon-plus"></span>
            <span><%= t "task.create" %></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show_member.html.erb
<% provide :title, @project.name %>
<h1 class="my-4"><%= @project.name %></h1>
<div class="row">
  <div class="col-lg-6 col-md-6 col-sm-7 col-centered">
    <h2><%= t "member.member" %></h2>
    <% @member.each do |item| %>
      <%= link_to user_path(item.id) do %>
        <% if is_project_manager? && (item.id != current_user.id) %>
          <div class="btn-group" role="group" aria-label="Delete">
            <button type="button" class="btn <%= manager_hightlight item %>">
              <%= item.name %>
            </button>
            <%= link_to delete_member_project_path(:user_id => item.id),
              method: :delete do %>
              <button type="  button" class="btn btn-danger" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            <% end %>
          </div>
        <% else %>
          <button class="btn <%= manager_hightlight item %>">
            <%= item.name %>
          </button>
        <% end %>
      <% end %>
    <% end %>
    <% if is_project_manager? %>
      <%= form_tag add_member_project_path do  %>
        <%= label_tag :email %>
        <%= email_field_tag :email, nil, class: "form-control" %>
        <%= submit_tag t("member.add_member"), class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>