config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "session#new"
  post "/login", to: "session#create"
  delete "/logout", to: "session#destroy"
  resources :users
  resources :projects do
    resources :tasks, only: %i(create destroy new) do
      resources :cards, only: %i(new create)
    end
    member do
      get "/show_member", to: "projects#show_member"
      post "/add_member", to: "projects#add_member"
      delete "/delete_member", to: "projects#remove_member"
    end
  end
  resources :cards, only: %i(show edit update destroy) do
    resources :events, only: %i(create), shallow: true
    member do
      post "/assign/:user_id", to: "assign#create", :as => "assign"
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("static.source_code"), Settings.static.link_to_github %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static.about"), about_path %></li>
      <li><%= link_to t("static.contact"), contact_path %></li>
    </ul>
  </nav>
</footer>
<br>
<%= link_to t("static.english"), locale: "en" %>
<%= link_to t("static.vietnamese"), locale: "vi" %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("nameproject"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to t("static.home"), root_path %>
        </li>
        <li>
          <%= link_to t("static.help"), help_path %>
        </li>
        <% if logged_in? %><li>
            <%= link_to t("side_bar.project"), projects_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("static.profile"), current_user %></li>
              <li><%= link_to t("static.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("static.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("static.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= favicon_link_tag asset_path("favicon.ico"), :rel => "icon", :type => "image/x-icon" %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t "static.body_tilte" %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container page-content">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t "static.body_tilte" %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "shared/show_flash" %>
    <div id="wrapper" class="toggled position">
      <%= render "shared/side_bar" %>
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/user_working.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %> | <%= t "static.body_tilte" %></title>
  <%= render "layouts/rails_default" %>
  <%= render "layouts/shim" %>
</head>
<body>
<%= render "shared/show_flash" %>
<div id="wrapper" class="toggled position">
  <%= render "shared/side_bar_working" %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>